const projectTypes = {
  ADD_NEW_PROJECT_START: "ADD_NEW_PROJECT_START",
  FETCH_PROJECTS_START: "FETCH_PROJECTS_START",
  SET_PROJECTS: "SET_PROJECTS",
  DELETE_PROJECT_START: "DELETE_PROJECT_START",
  SET_CURRENT_PROJECT_ID: "SET_CURRENT_PROJECT_ID",
  UPDATE_APPLIANCES_START: "UPDATE_APPLIANCES_START",
  UPDATE_DATABASES_START: "UPDATE_DATABASES_START",
  UPDATE_STORAGE_START: "UPDATE_STORAGE_START",
  UPDATE_VMS_START: "UPDATE_VMS_START",
  FETCH_POWER_VALUES_START: "FETCH_POWER_VALUES_START",
  SET_CURRENT_POWER_VALUES: "SET_CURRENT_POWER_VALUES",
  SET_PROJECT_REPORT: "SET_PROJECT_REPORT",
  UPDATE_PROJECT_PROPERTY: "UPDATE_PROJECT_PROPERTY",
  ADD_NEW_SENSOR_START: "ADD_NEW_SENSOR_START",
  DELETE_SENSOR_START: "DELETE_SENSOR_START",
  SET_ZABBIX_TOKEN_START: "SET_ZABBIX_TOKEN_START",
};

export default projectTypes;
